### ISSUE TITLE
Simulation : Find rules

### ISSUE THREAD

**Issue by kz2wd** [AlexisMoins/tsukuba-gdmc-2022#33]
- Description
- How they interact with the world
- How they interact with minecraft

**Comment by kz2wd** [comment]
My first idea :

- The city contains buildings
- Buildings can host a certain amount of agent
- Agent generate work points
- A Building can have a profession, the agent in it will generate more point based on the environment of the building (ex: lumberjack, amount of tree nearby)
- Each turn : 
1. The city can increase agent amount if there are enough building to host them
2. The city can use its work points to add a building

Problem : 
Does it really need to be a simulation ? Can't it just be a 'sequence' ? Why bothering with agent and points and stuff to place structure when we already use a 'score' system to get the best location ? Why not just buffing the score system to make it incredible ?

I would say, the answer could be the chaos of the simulation and the particularity of its outcome, but would it be that good or remarkable ? Could we take enough advantage of it ? We need more research.

**Comment by alexis-moins** [comment]
I like the idea of work points and filling buildings with agents!

Some additional points to think about:
- To make the simulation worth, one might want to change the simulation's parameters on the fly. To do so, calling the `main.py` script should take optional parameters like `debug`, `max_tick_speed`, `population`, `years` and others. We could do so easily by using third party packages like [click](https://click.palletsprojects.com/en/8.1.x/)
